# Generated by Django 4.0.2 on 2022-02-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='default_user_image', upload_to='static/images/user_images/'),
        ),
    ]
